name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test
      - run: yarn run build --if-present
# name: Deploy to GCP
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
# jobs:
#   publish:
#     name: Publish index.js for general use
#     runs-on: ubuntu-latest
#     steps:
#       - name: Wait for tests & build to succeed
#         uses: lewagon/wait-on-check-action@v1.0.0
#         with:
#           ref: ${{ github.ref }}
#           check-name: "Test"
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           wait-interval: 10
#           allowed-conclusions: success,skipped,cancelled

#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - run: yarn
#       - run: yarn parcel build src/index.tsx --no-source-maps --dist-dir docs

#       - id: 'auth'
#       uses: 'google-github-actions/auth@v0'
#       with:
#         workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
#         service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

#       - id: 'upload-file'
#         uses: 'google-github-actions/upload-cloud-storage@v0'
#         with:
#           path: 'src/docs/index.js'
#           destination: 'buckety-mc-bucket-face'

#       - id: 'uploaded-files'
#         uses: 'foo/bar@main'
#         env:
#           file: '${{ steps.upload-file.outputs.uploaded }}'
